stack:
    common:
        project-name: hackathon
        secret-name: hcktn
        domain-name: bomba.by

    jenkins:
        description: "Jenkins Service"
        chart-version: stable/jenkins
        config: vars/jenkins.yml
        order: 1
        service_port: 8080
        service_name: jenkins
        ingress: yes

    prometheus:
        description: "Monitoring Service"
        chart-version: stable/prometheus
        config: vars/prometheus.yml
        order: 2
        service_port: 80
        service_name: prometheus-server
        ingress: yes

    grafana:
        description: "Dashboard Service"
        chart-version: stable/grafana
        config: vars/grafana.yml
        order: 3
        service_port: 80
        service_name: grafana
        ingress: yes

    nginx:
        description: "Stack WEB Front-End/Proxy"
        chart-version: stable/nginx-ingress
        assign_dns:
            - jenkins
            - prometheus
            - grafana
            - release
            - test
        order: 4

    kube-lego:
        description: "Let's encrypt management"
        kub-service-name: kube-lego
        config: vars/lego.yml
        order: 5

    ingress:
        description: "Nginx Virtual Hosts configs"
        kub-service-name: ingress
        config: vars/ingress.yml.j2
        order: 6

    release:
        order: -1 # don't deploy with make file
        service_port: 8080
        service_name: release
        ingress: yes

    lekube:
        kub-service-name: logentries
        config: vars/logentries.yml
        order: 7

 
